import { useState } from "react";
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";

type Screen = "splash" | "login" | "register" | "home" | "profile";

export default function App() {
  const [screen, setScreen] = useState<Screen>("splash");
  const [email, setEmail] = useState("");
  const isSignedIn = screen === "home" || screen === "profile";

  if (screen === "splash") return <SafeAreaView style={styles.center}><Text style={styles.logo}>balkan<Text style={styles.blue}>.works</Text></Text><Text style={styles.tagline}>Sve što ti treba, lokalno i pametno.</Text><Action label="Počni" onPress={() => setScreen("login")} /><Pressable onPress={() => setScreen("login")}><Text style={styles.link}>Već imam nalog</Text></Pressable></SafeAreaView>;

  return <SafeAreaView style={styles.safe}>
    {isSignedIn ? <>
      <View style={styles.header}><Text style={styles.logo}>balkan<Text style={styles.blue}>.works</Text></Text><Text style={styles.location}>⌖ Beograd</Text></View>
      {screen === "home" ? <View style={styles.content}><Text style={styles.eyebrow}>BALKAN AI</Text><Text style={styles.title}>Šta ti treba danas?</Text><Pressable style={styles.search}><Text>✦ Treba mi servis za auto blizu mene</Text><Text style={styles.blue}>›</Text></Pressable><Text style={styles.section}>Popularno</Text><View style={styles.grid}>{["🍽 Hrana", "🚗 Auto", "🏠 Dom", "♥ Zdravlje"].map((item) => <View key={item} style={styles.card}><Text>{item}</Text></View>)}</View><Text style={styles.section}>Preporučeno za tebe</Text><View style={styles.business}><Text style={styles.businessTitle}>Premium Auto Servis</Text><Text style={styles.muted}>★★★★★ 4.9 · 1,5 km · Verifikovano</Text><Text style={styles.ai}>✦ AI preporuka za tvoju pretragu</Text></View></View> : <View style={styles.content}><View style={styles.avatar}><Text style={styles.avatarText}>MP</Text></View><Text style={styles.title}>Marko Petrović</Text><Text style={styles.muted}>Upravljaj nalogom, lokacijom i interesovanjima.</Text><View style={styles.business}><Text style={styles.businessTitle}>Moj nalog</Text><Text style={styles.menu}>Lični podaci ›</Text><Text style={styles.menu}>Lokacija ›</Text><Text style={styles.menu}>Podešavanja ›</Text></View></View>}
      <View style={styles.nav}><Nav label="Početna" active={screen === "home"} onPress={() => setScreen("home")} /><Nav label="AI" active={false} onPress={() => setScreen("home")} /><Nav label="Profil" active={screen === "profile"} onPress={() => setScreen("profile")} /></View>
    </> : <View style={styles.auth}><Text style={styles.logo}>balkan<Text style={styles.blue}>.works</Text></Text><Text style={styles.title}>{screen === "login" ? "Prijavi se" : "Napravi nalog"}</Text><TextInput autoCapitalize="none" keyboardType="email-address" placeholder="Email" style={styles.input} value={email} onChangeText={setEmail} /><TextInput secureTextEntry placeholder="Lozinka" style={styles.input} /><Action label={screen === "login" ? "Prijavi se" : "Registruj se"} onPress={() => setScreen("home")} /><Pressable onPress={() => setScreen(screen === "login" ? "register" : "login")}><Text style={styles.link}>{screen === "login" ? "Nemaš nalog? Registruj se" : "Već imaš nalog? Prijavi se"}</Text></Pressable></View>}
  </SafeAreaView>;
}

function Action({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable style={styles.action} onPress={onPress}><Text style={styles.actionText}>{label}</Text></Pressable>; }
function Nav({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress}><Text style={[styles.navText, active && styles.navActive]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f6f9fe" }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28, backgroundColor: "#f6f9fe" }, auth: { flex: 1, justifyContent: "center", padding: 26, gap: 14, backgroundColor: "#f6f9fe" }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 20, backgroundColor: "#fff" }, logo: { fontSize: 24, fontWeight: "800", color: "#102a56" }, blue: { color: "#2563eb" }, tagline: { marginTop: 12, marginBottom: 24, color: "#58677f", textAlign: "center" }, title: { marginTop: 10, color: "#102a56", fontSize: 30, fontWeight: "800" }, eyebrow: { marginTop: 20, color: "#7353dc", fontSize: 12, fontWeight: "800", letterSpacing: 1 }, content: { flex: 1, padding: 22 }, search: { marginTop: 20, flexDirection: "row", justifyContent: "space-between", padding: 18, borderRadius: 18, backgroundColor: "#fff", borderWidth: 1, borderColor: "#dce7f6" }, section: { marginTop: 28, marginBottom: 12, color: "#102a56", fontSize: 18, fontWeight: "800" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, card: { width: "47%", padding: 18, borderRadius: 16, backgroundColor: "#fff" }, business: { marginTop: 8, padding: 18, borderRadius: 18, backgroundColor: "#fff", borderWidth: 1, borderColor: "#dce7f6", gap: 8 }, businessTitle: { color: "#102a56", fontSize: 17, fontWeight: "800" }, muted: { color: "#58677f" }, ai: { color: "#7353dc", fontWeight: "700" }, input: { padding: 15, borderRadius: 14, borderWidth: 1, borderColor: "#dce7f6", backgroundColor: "#fff" }, action: { alignItems: "center", marginTop: 8, padding: 16, borderRadius: 14, backgroundColor: "#2563eb" }, actionText: { color: "#fff", fontWeight: "800" }, link: { color: "#2563eb", textAlign: "center", fontWeight: "700" }, location: { color: "#58677f" }, nav: { flexDirection: "row", justifyContent: "space-around", padding: 18, backgroundColor: "#fff", borderTopWidth: 1, borderColor: "#dce7f6" }, navText: { color: "#7f8da3", fontWeight: "700" }, navActive: { color: "#2563eb" }, avatar: { alignItems: "center", justifyContent: "center", width: 72, height: 72, borderRadius: 24, backgroundColor: "#2563eb" }, avatarText: { color: "#fff", fontWeight: "800", fontSize: 21 }, menu: { color: "#102a56", paddingVertical: 7 } });
