const adminState = { password: sessionStorage.getItem('majstorAdminPassword') || '', view: 'overview' };
const adminLogin = document.querySelector('#adminLogin'); const adminApp = document.querySelector('#adminApp'); const adminView = document.querySelector('#adminView'); const adminStatus = document.querySelector('#adminStatus');
function esc(value) { return String(value || '').replace(/[&<>'"]/g, function (character) { return ({ '&': '&amp;', '<': '&gt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]; }); }
function labelStatus(value) { return ({ open: 'Primljeno', in_progress: 'U obradi', resolved: 'Rešeno' })[value] || value || '—'; }
async function adminRequest(path, options) { const response = await fetch(path, Object.assign({ headers: { 'x-admin-password': adminState.password } }, options || {})); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Administratorski zahtev nije uspeo.'); return body; }
function table(headers, rows) { return rows.length ? '<table class="admin-table"><thead><tr>' + headers.map(function (item) { return '<th>' + item + '</th>'; }).join('') + '</tr></thead><tbody>' + rows.join('') + '</tbody></table>' : '<p class="admin-empty">Nema podataka za prikaz.</p>'; }
function renderOverview(data) { const s = data.stats; adminView.innerHTML = '<div class="admin-stats"><article class="admin-stat"><b>' + s.users + '</b><span>korisnika</span></article><article class="admin-stat"><b>' + s.providers + '</b><span>majstora</span></article><article class="admin-stat"><b>' + s.openJobs + '</b><span>otvorenih poslova</span></article><article class="admin-stat"><b>' + s.activeJobs + '</b><span>aktivnih radova</span></article><article class="admin-stat"><b>' + s.openTickets + '</b><span>otvorenih tiketa</span></article></div><div class="admin-grid"><article class="admin-card"><h2>Poslednji poslovi</h2>' + table(['Zanat', 'Lokacija', 'Status'], (data.jobs || []).map(function (job) { return '<tr><td><b>' + esc(job.category) + '</b></td><td>' + esc(job.location) + '</td><td>' + esc(job.status) + '</td></tr>'; })) + '</article><article class="admin-card"><h2>Podrška</h2>' + table(['Tema', 'Status'], (data.tickets || []).map(function (ticket) { return '<tr><td><b>' + esc(ticket.subject) + '</b></td><td>' + esc(labelStatus(ticket.status)) + '</td></tr>'; })) + '</article></div>'; }
async function renderJobs() { const jobs = await adminRequest('/api/admin/jobs'); adminView.innerHTML = '<article class="admin-card"><h2>Svi poslovi</h2>' + table(['Zanat', 'Lokacija', 'Tok', 'Moderacija'], jobs.map(function (job) { return '<tr><td><b>' + esc(job.category) + '</b><br /><small>' + esc(job.description).slice(0, 70) + '</small></td><td>' + esc(job.location) + '</td><td>' + esc(job.status) + '</td><td><button class="job-flag ' + (job.adminFlag ? 'flagged' : '') + '" data-id="' + esc(job.id) + '" data-flag="' + (!job.adminFlag) + '">' + (job.adminFlag ? 'Ukloni proveru' : 'Označi za proveru') + '</button></td></tr>'; })) + '</article>'; adminView.querySelectorAll('.job-flag').forEach(function (button) { button.addEventListener('click', async function () { await adminRequest('/api/admin/jobs/' + button.dataset.id + '/flag', { method: 'POST', headers: { 'x-admin-password': adminState.password, 'Content-Type': 'application/json' }, body: JSON.stringify({ flagged: button.dataset.flag === 'true' }) }); loadView(); }); }); }
async function renderUsers() { const users = await adminRequest('/api/admin/users'); adminView.innerHTML = '<article class="admin-card"><h2>Korisnici i majstori</h2>' + table(['Ime', 'Uloga', 'Grad', 'Verifikacija', 'Detalji'], users.map(function (user) { const provider = user.provider; return '<tr><td><b>' + esc(user.full_name) + '</b><br /><small>' + esc(user.created_at || '') + '</small></td><td>' + esc(user.role === 'provider' ? 'Majstor' : user.role === 'admin' ? 'Admin' : 'Klijent') + '</td><td>' + esc(user.city || '—') + '</td><td>' + (user.phone_verified ? 'Telefon ✓' : 'Telefon —') + '<br />' + (user.identity_verified ? 'Identitet ✓' : 'Identitet —') + '</td><td>' + (provider ? esc(provider.trade) + '<br />★ ' + esc(provider.rating) + ' · ' + esc(provider.review_count) + ' ocena' : '—') + '</td></tr>'; })) + '</article>'; }
async function renderSupport() { const tickets = await adminRequest('/api/admin/support'); adminView.innerHTML = '<article class="admin-card"><h2>Podrška i prijave</h2>' + table(['Tema i poruka', 'Kreirano', 'Status'], tickets.map(function (ticket) { return '<tr><td><b>' + esc(ticket.subject) + '</b><br /><small>' + esc(ticket.message) + '</small></td><td>' + esc(ticket.createdAt || ticket.created_at || '') + '</td><td><select class="ticket-status" data-id="' + esc(ticket.id) + '"><option value="open"' + (ticket.status === 'open' || ticket.status === 'Primljeno' ? ' selected' : '') + '>Primljeno</option><option value="in_progress"' + (ticket.status === 'in_progress' || ticket.status === 'U obradi' ? ' selected' : '') + '>U obradi</option><option value="resolved"' + (ticket.status === 'resolved' || ticket.status === 'Rešeno' ? ' selected' : '') + '>Rešeno</option></select></td></tr>'; })) + '</article>'; adminView.querySelectorAll('.ticket-status').forEach(function (select) { select.addEventListener('change', async function () { await adminRequest('/api/admin/support/' + select.dataset.id, { method: 'POST', headers: { 'x-admin-password': adminState.password, 'Content-Type': 'application/json' }, body: JSON.stringify({ status: select.value }) }); adminStatus.textContent = 'Status tiketa je sačuvan.'; }); }); }
function renderAi() { adminView.innerHTML = '<div class="admin-ai"><article><b>3</b><p>AI saveta dnevno po korisničkoj mreži.</p></article><article><b>50</b><p>Ukupan AI limit platforme po danu.</p></article><article><b>15 USD</b><p>Projektni limit u OpenAI nalogu — prati ga i putem alertova.</p></article></div><article class="admin-card" style="margin-top:16px"><h2>Zaštita AI potrošnje</h2><p class="admin-empty">Server ograničava zahteve pre slanja ka OpenAI-ju. Vrednosti se mogu promeniti kroz Render varijable <b>AI_DAILY_LIMIT_PER_IP</b> i <b>AI_DAILY_LIMIT_GLOBAL</b>.</p></article>'; }
async function loadView() { const titles = { overview: 'Pregled platforme', jobs: 'Upravljanje poslovima', users: 'Korisnici i majstori', support: 'Podrška i prijave', ai: 'AI i limiti' }; document.querySelector('#adminTitle').textContent = titles[adminState.view]; adminStatus.textContent = 'Učitavanje…'; try { if (adminState.view === 'overview') renderOverview(await adminRequest('/api/admin/overview')); else if (adminState.view === 'jobs') await renderJobs(); else if (adminState.view === 'users') await renderUsers(); else if (adminState.view === 'support') await renderSupport(); else renderAi(); adminStatus.textContent = 'Podaci su osveženi.'; } catch (error) { adminStatus.textContent = error.message; } }
document.querySelector('#adminLoginForm').addEventListener('submit', async function (event) { event.preventDefault(); adminState.password = document.querySelector('#adminPassword').value; document.querySelector('#adminLoginError').classList.add('hidden'); try { await adminRequest('/api/admin/overview'); sessionStorage.setItem('majstorAdminPassword', adminState.password); adminLogin.classList.add('hidden'); adminApp.classList.remove('hidden'); loadView(); } catch (error) { const box = document.querySelector('#adminLoginError'); box.textContent = error.message + ' Proveri ADMIN_PASSWORD u Render-u.'; box.classList.remove('hidden'); } });
document.querySelectorAll('.admin-nav nav button').forEach(function (button) { button.addEventListener('click', function () { document.querySelectorAll('.admin-nav nav button').forEach(function (item) { item.classList.remove('active'); }); button.classList.add('active'); adminState.view = button.dataset.view; loadView(); }); });
document.querySelector('#adminRefresh').addEventListener('click', loadView); document.querySelector('#adminLogout').addEventListener('click', function () { sessionStorage.removeItem('majstorAdminPassword'); adminState.password = ''; adminApp.classList.add('hidden'); adminLogin.classList.remove('hidden'); document.querySelector('#adminPassword').value = ''; });
if (adminState.password) { adminLogin.classList.add('hidden'); adminApp.classList.remove('hidden'); loadView(); }
