const I18N = {
  sr:{navServices:'Usluge',navTrust:'Bezbednost',navTrades:'Majstor odmah',eyebrow:'JEDNA APLIKACIJA ZA SVAKI DAN',heroTitle:'Sve što ti treba<br />u <em>tvom kraju.</em>',heroLead:'Pouzdane lokalne usluge, stanovanje, auto i termini — na jednom jasnom mestu.',searchPlaceholder:'Pretraži majstora, stan, servis ili termin',search:'Pretraži',searchHint:'Probaj: „vodoinstalater”, „cimer”, „registracija auta”',orbitMain:'Tvoj lokalni svet',orbitSub:'proveren i bliži',trades:'Majstori',housing:'Stanovi',auto:'Auto',queues:'Termini',servicesEyebrow:'IZABERI ŠTA TI TREBA',servicesTitle:'Jedan nalog, mnogo lakši dan.',servicesCopy:'Svaki modul je napravljen da smanji čekanje, prevare i pozivanje na deset strana.',workspaceLabel:'BRZI PREGLED',trustEyebrow:'POVERENJE JE OSNOVA',trustTitle:'Manje rizika.<br />Više završenih stvari.',trustOne:'Verifikovani profili',trustOneCopy:'Jasan identitet, ocene i istorija saradnje gde je usluga dostupna.',trustTwo:'Lokalno i jasno',trustTwoCopy:'Grad, okvirna cena i dostupnost pre nego što pošalješ zahtev.',trustThree:'Tvoj izbor',trustThreeCopy:'Uporedi ponude i ocenjuj iskustvo nakon završenog posla.',footer:'Lokalne stvari, uređene za ljude.',openTrades:'Otvori Majstor odmah →',open:'Otvori modul →',new:'NOVO'},
  hr:{navServices:'Usluge',navTrust:'Sigurnost',navTrades:'Majstor odmah',eyebrow:'JEDNA APLIKACIJA ZA SVAKI DAN',heroTitle:'Sve što trebaš<br />u <em>svom kraju.</em>',heroLead:'Pouzdane lokalne usluge, stanovanje, auto i termini — na jednom jasnom mjestu.',searchPlaceholder:'Pretraži majstora, stan, servis ili termin',search:'Pretraži',searchHint:'Pokušaj: „vodoinstalater”, „cimer”, „registracija auta”',orbitMain:'Tvoj lokalni svijet',orbitSub:'provjeren i bliži',trades:'Majstori',housing:'Stanovi',auto:'Auto',queues:'Termini',servicesEyebrow:'ODABERI ŠTO TI TREBA',servicesTitle:'Jedan račun, puno lakši dan.',servicesCopy:'Svaki modul smanjuje čekanje, prevare i pozive na deset strana.',workspaceLabel:'BRZI PREGLED',trustEyebrow:'POVJERENJE JE TEMELJ',trustTitle:'Manje rizika.<br />Više riješenih stvari.',trustOne:'Provjereni profili',trustOneCopy:'Jasan identitet, ocjene i povijest suradnje gdje je usluga dostupna.',trustTwo:'Lokalno i jasno',trustTwoCopy:'Grad, okvirna cijena i dostupnost prije slanja zahtjeva.',trustThree:'Tvoj izbor',trustThreeCopy:'Usporedi ponude i ocijeni iskustvo nakon završetka.',footer:'Lokalne stvari, uređene za ljude.',openTrades:'Otvori Majstor odmah →',open:'Otvori modul →',new:'NOVO'},
  bs:{navServices:'Usluge',navTrust:'Sigurnost',navTrades:'Majstor odmah',eyebrow:'JEDNA APLIKACIJA ZA SVAKI DAN',heroTitle:'Sve što ti treba<br />u <em>tvom kraju.</em>',heroLead:'Pouzdane lokalne usluge, stanovanje, auto i termini — na jednom mjestu.',searchPlaceholder:'Pretraži majstora, stan, servis ili termin',search:'Pretraži',searchHint:'Probaj: „vodoinstalater”, „cimer”, „registracija auta”',orbitMain:'Tvoj lokalni svijet',orbitSub:'provjeren i bliži',trades:'Majstori',housing:'Stanovi',auto:'Auto',queues:'Termini',servicesEyebrow:'IZABERI ŠTA TI TREBA',servicesTitle:'Jedan nalog, mnogo lakši dan.',servicesCopy:'Svaki modul smanjuje čekanje, prevare i pozive na deset strana.',workspaceLabel:'BRZI PREGLED',trustEyebrow:'POVJERENJE JE OSNOVA',trustTitle:'Manje rizika.<br />Više završenih stvari.',trustOne:'Verifikovani profili',trustOneCopy:'Jasan identitet, ocjene i historija saradnje gdje je usluga dostupna.',trustTwo:'Lokalno i jasno',trustTwoCopy:'Grad, okvirna cijena i dostupnost prije slanja zahtjeva.',trustThree:'Tvoj izbor',trustThreeCopy:'Uporedi ponude i ocijeni iskustvo nakon završetka.',footer:'Lokalne stvari, uređene za ljude.',openTrades:'Otvori Majstor odmah →',open:'Otvori modul →',new:'NOVO'},
  en:{navServices:'Services',navTrust:'Safety',navTrades:'Majstor odmah',eyebrow:'ONE APP FOR EVERYDAY LIFE',heroTitle:'Everything you need<br />in <em>your area.</em>',heroLead:'Trusted local services, housing, car care and appointments — in one clear place.',searchPlaceholder:'Search for a trade, home, service or appointment',search:'Search',searchHint:'Try: “plumber”, “roommate”, “car registration”',orbitMain:'Your local world',orbitSub:'verified and closer',trades:'Trades',housing:'Housing',auto:'Car',queues:'Appointments',servicesEyebrow:'CHOOSE WHAT YOU NEED',servicesTitle:'One account, an easier day.',servicesCopy:'Every module is built to reduce waiting, fraud and calls in ten directions.',workspaceLabel:'QUICK VIEW',trustEyebrow:'TRUST COMES FIRST',trustTitle:'Less risk.<br />More things done.',trustOne:'Verified profiles',trustOneCopy:'Clear identity, ratings and service history wherever it is available.',trustTwo:'Local and clear',trustTwoCopy:'City, estimated price and availability before you send a request.',trustThree:'Your choice',trustThreeCopy:'Compare offers and rate your experience once the work is done.',footer:'Local life, arranged for people.',openTrades:'Open Majstor odmah →',open:'Open module →',new:'NEW'},
  mk:{navServices:'Услуги',navTrust:'Безбедност',navTrades:'Majstor odmah',eyebrow:'ЕДНА АПЛИКАЦИЈА ЗА СЕКОЈ ДЕН',heroTitle:'Сè што ти треба<br />во <em>твојот крај.</em>',heroLead:'Локални услуги, домување, автомобил и термини — на едно јасно место.',searchPlaceholder:'Пребарај мајстор, стан, сервис или термин',search:'Пребарај',searchHint:'Пробај: „водоводџија”, „цимер”, „регистрација”',orbitMain:'Твојот локален свет',orbitSub:'проверен и поблизок',trades:'Мајстори',housing:'Домови',auto:'Авто',queues:'Термини',servicesEyebrow:'ИЗБЕРИ ШТО ТИ ТРЕБА',servicesTitle:'Еден профил, полесен ден.',servicesCopy:'Секој модул го намалува чекањето и несигурноста.',workspaceLabel:'БРЗ ПРЕГЛЕД',trustEyebrow:'ДОВЕРБАТА Е ОСНОВА',trustTitle:'Помалку ризик.<br />Повеќе завршени работи.',trustOne:'Проверени профили',trustOneCopy:'Јасен идентитет и оцени каде што услугата е достапна.',trustTwo:'Локално и јасно',trustTwoCopy:'Град, цена и достапност пред барањето.',trustThree:'Твој избор',trustThreeCopy:'Спореди понуди и оцени по завршувањето.',footer:'Локални работи, направени за луѓе.',openTrades:'Отвори Majstor odmah →',open:'Отвори модул →',new:'НОВО'},
  sq:{navServices:'Shërbimet',navTrust:'Siguria',navTrades:'Majstor odmah',eyebrow:'NJË APLIKACION PËR ÇDO DITË',heroTitle:'Gjithçka që të duhet<br />në <em>zonën tënde.</em>',heroLead:'Shërbime lokale të besueshme, banim, makinë dhe termine — në një vend të qartë.',searchPlaceholder:'Kërko mjeshtër, banesë, servis ose termin',search:'Kërko',searchHint:'Provo: “hidraulik”, “bashkëbanues”, “regjistrim makine”',orbitMain:'Bota jote lokale',orbitSub:'e verifikuar dhe pranë',trades:'Mjeshtër',housing:'Banim',auto:'Makinë',queues:'Termine',servicesEyebrow:'ZGJIDH ÇFARË TË DUHET',servicesTitle:'Një llogari, një ditë më e lehtë.',servicesCopy:'Çdo modul ul pritjen dhe pasigurinë.',workspaceLabel:'PAMJE E SHPEJTË',trustEyebrow:'BESIMI ËSHTË BAZA',trustTitle:'Më pak rrezik.<br />Më shumë punë të kryera.',trustOne:'Profile të verifikuara',trustOneCopy:'Identitet dhe vlerësime të qarta ku shërbimi është i disponueshëm.',trustTwo:'Lokale dhe e qartë',trustTwoCopy:'Qyteti, çmimi dhe disponueshmëria para kërkesës.',trustThree:'Zgjedhja jote',trustThreeCopy:'Krahaso oferta dhe vlerëso përvojën.',footer:'Jeta lokale, e organizuar për njerëzit.',openTrades:'Hap Majstor odmah →',open:'Hap modulin →',new:'E RE'}
};

const modules = [
  {id:'trades',icon:'⚒',title:'Majstor odmah',description:'Majstori sa ocenama, dostupnošću, ponudama i chatom.',tag:'Aktivno',action:'Otvori Majstor odmah',link:'index.html'},
  {id:'housing',icon:'⌂',title:'Stanovi i cimeri',description:'Provereni oglasi, cimer profili i pregled zajedničkih troškova.',tag:'U pripremi',action:'Pogledaj stanove'},
  {id:'local',icon:'✦',title:'Lokalne usluge',description:'Frizeri, privatni časovi, vulkanizeri i servisi iz tvog kraja.',tag:'U pripremi',action:'Istraži usluge'},
  {id:'auto',icon:'▣',title:'Sve za auto',description:'Servis, tehnički pregled, registracija, parking i podsetnici.',tag:'U pripremi',action:'Otvori auto centar'},
  {id:'queues',icon:'◷',title:'Redovi i termini',description:'Prikaz gužve i zahtev za termin kod povezanih ustanova.',tag:'U pripremi',action:'Proveri termine'},
  {id:'payments',icon:'◉',title:'Računi i plaćanja',description:'Jedno mesto za račune i plaćanja kada se povežu licencirani partneri.',tag:'Sledeća faza',action:'Saznaj više'}
];
const details = {
  trades:{title:'Majstori koji odgovaraju kada ti trebaju.',copy:'Već radi: pretraga po lokaciji, zahtevi za posao, ponude, poruke, portfolio, GPS zona, ocene i administracija.',items:[['⚡','Dostupni majstori','po zanimanju i lokaciji'],['★','Uzajamne ocene','nakon završenog posla'],['⌕','Pametna pretraga','majstor, zanat ili kraj']]},
  housing:{title:'Stanovanje bez sumnjivih oglasa.',copy:'MVP će imati potvrđene profile izdavača i cimera, pregled režija i prijavu sumnjivog oglasa. Ne objavljujemo izmišljene oglase.',items:[['✓','Identitet izdavača','verifikacija pre oznake poverenja'],['⌂','Troškovi na jednom mestu','kirija, režije i dogovor cimera'],['⚑','Prijava oglasa','brza provera administracije']]},
  local:{title:'Usluge koje su zaista u blizini.',copy:'Lokalni pružaoci usluga dobijaju profil, raspored, ocene i direktan zahtev. Počinjemo od gradova gde imamo proveru kvaliteta.',items:[['✦','Više kategorija','frizer, časovi, auto i još mnogo'],['◷','Slobodni termini','bez pozivanja na deset brojeva'],['★','Javne ocene','posle potvrđene usluge']]},
  auto:{title:'Tvoj auto, bez propuštenih rokova.',copy:'Servisni podsetnici, tehnički pregled, registracija, parking i provera ponuda servisa su sledeći praktični modul.',items:[['▣','Servisna istorija','u tvom privatnom nalogu'],['◷','Pametni podsetnici','za rokove koje sam biraš'],['⌕','Uporedi servise','po lokaciji i oceni']]},
  queues:{title:'Vreme je vrednije od reda.',copy:'Prikaz gužve i rezervacija dolaze samo kroz zvanično povezane ustanove. Do tada ovaj modul jasno označava demo i ne obećava državni termin.',items:[['◷','Stanje gužve','od potvrđenih partnera'],['✓','Zvanične veze','kada ih ustanova odobri'],['⚑','Jasno označen demo','bez lažnih rezervacija']]},
  payments:{title:'Plaćanja tek kada su bezbedna i licencirana.',copy:'Plaćanje računa, dostava i transferi zahtevaju banku ili licenciranog platnog partnera. Zato se ovaj modul uvodi postepeno, bez rizika za korisnike.',items:[['◉','Licencirani partneri','obavezni za pravi promet'],['✓','Jasne naknade','pre svake potvrde'],['⌁','Tvoja kontrola','bez čuvanja kartice u demou']]}
};
let language = localStorage.getItem('balkan-language') || 'sr';
let selected = 'trades';
let toastTimer;
const t = key => I18N[language]?.[key] ?? I18N.en[key] ?? key;
function setText() { document.documentElement.lang = language === 'sr' ? 'sr-Latn' : language; document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n)); document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder)); document.getElementById('languageSelect').value=language; renderModules(); renderWorkspace(); }
function renderModules(filter='') { const q=filter.trim().toLocaleLowerCase(); const visible=modules.filter(m=>!q || `${m.title} ${m.description} ${m.id}`.toLocaleLowerCase().includes(q)); const grid=document.getElementById('moduleGrid'); grid.innerHTML=visible.map(m=>`<button class="module-card ${m.id===selected?'active':''}" type="button" data-module="${m.id}"><span class="module-icon">${m.icon}</span><h3>${m.title}</h3><p>${m.description}</p><small>${m.tag.toUpperCase()} · ${m.id==='trades'?t('open'):t('new')}</small></button>`).join('') || `<p style="color:#657970">Nema modula za ovaj pojam. Probaj „majstor”, „stan”, „auto” ili „termin”.</p>`; }
function renderWorkspace(){const d=details[selected];const current=modules.find(m=>m.id===selected);document.getElementById('workspaceContent').innerHTML=`<div class="workspace-view"><div class="workspace-copy"><h2>${d.title}</h2><p>${d.copy}</p>${current.link?`<a class="workspace-action" href="${current.link}">${current.action} <span>→</span></a>`:`<button class="workspace-action" data-demo-action="${selected}">${current.action} <span>→</span></button>`}</div><div class="workspace-preview"><div class="preview-top"><span>${current.icon} ${current.title}</span><span class="preview-badge">${current.tag}</span></div><div class="preview-list">${d.items.map(i=>`<div class="preview-item"><span>${i[0]} ${i[1]}</span><b>${i[2]}</b></div>`).join('')}</div></div></div>`;}
function showToast(message){const toast=document.getElementById('hubToast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),4200);}
document.getElementById('moduleGrid').addEventListener('click',event=>{const card=event.target.closest('[data-module]');if(!card)return;selected=card.dataset.module;renderModules(document.getElementById('hubSearch').value);renderWorkspace();document.getElementById('hubWorkspace').scrollIntoView({behavior:'smooth',block:'center'});});
document.getElementById('workspaceContent').addEventListener('click',event=>{const action=event.target.closest('[data-demo-action]');if(action)showToast('Ovaj modul je spreman za sledeću fazu. Sada prikupljamo proverene partnere i pravila za bezbedno pokretanje.');});
document.getElementById('hubSearchForm').addEventListener('submit',event=>{event.preventDefault();const q=document.getElementById('hubSearch').value;renderModules(q);document.getElementById('usluge').scrollIntoView({behavior:'smooth',block:'start'});showToast(q?`Prikazani su moduli povezani sa: ${q}`:'Prikazujemo sve module.');});
document.getElementById('languageSelect').addEventListener('change',event=>{language=event.target.value;localStorage.setItem('balkan-language',language);setText();});
document.getElementById('citySelect').addEventListener('change',event=>{localStorage.setItem('balkan-city',event.target.value);showToast(`Lokacija je postavljena na: ${event.target.value}`);});
document.getElementById('citySelect').value=localStorage.getItem('balkan-city') || 'Novi Sad';
setText();
