packages:
  - "."
  - "apps/*"
  - "services/*"
  - "packages/*"
overrides:
  hono: 4.12.25
  '@xmldom/xmldom': 0.9.10
  lodash: 4.18.1
  tar: 7.5.11
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  msw: false
  prisma: true
  sharp: true
