'use client'

import Link from 'next/link'
import { CheckCircle2, Clock3, FileCheck2, Mail, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'

type Application = { id: string; name: string; email: string; type: string; plan: string; status: string; submittedAt: string }

export default function PartnerStatusPage() {
  const [application, setApplication] = useState<Application | null>(null)
  useEffect(() => { const stored = window.localStorage.getItem('balkanworks-partner-application'); if (stored) setApplication(JSON.parse(stored) as Application) }, [])
  const status = application?.status ?? 'NA_CEKANJU'
  const approved = status === 'ODOBREN'
  const rejected = status === 'ODBIJEN'
  const title = approved ? 'Partnerstvo je odobreno' : rejected ? 'Prijava partnera nije odobrena' : 'Prijava partnera je na proveri'
  const statusLabel = approved ? 'Partner je odobren' : rejected ? 'Prijava je odbijena' : 'Na čekanju odobrenja'
  const statusIcon = approved ? <CheckCircle2 className="size-4 text-emerald-600" /> : rejected ? <ShieldCheck className="size-4 text-rose-600" /> : <Clock3 className="size-4 text-primary" />
  return <main className="min-h-screen bg-gradient-to-b from-secondary/60 to-background px-4 py-10"><div className="mx-auto max-w-2xl"><Link href="/" className="text-sm font-semibold text-primary">← Nazad na sajt</Link><section className="mt-8 rounded-3xl border border-border bg-card p-6 shadow-card sm:p-8"><span className={`grid size-12 place-items-center rounded-2xl ${approved ? 'bg-emerald-50 text-emerald-600' : rejected ? 'bg-rose-50 text-rose-600' : 'bg-primary/10 text-primary'}`}>{approved ? <CheckCircle2 className="size-6" /> : rejected ? <ShieldCheck className="size-6" /> : <Clock3 className="size-6" />}</span><h1 className="mt-5 text-3xl font-bold text-navy">{application ? title : 'Proveri status partnerstva'}</h1>{application ? <><p className="mt-2 text-muted-foreground">Prijavu za <strong className="text-navy">{application.name}</strong> primili smo {application.submittedAt}. {approved ? 'Partner nalog može preći na aktivaciju kampanja i paketa.' : rejected ? 'Kontaktirajte podršku za dodatne informacije ili podnesite dopunjenu prijavu.' : 'Administracija proverava podatke, paket i usklađenost sa pravilima platforme.'}</p><div className={`mt-6 rounded-2xl border p-4 ${approved ? 'border-emerald-200 bg-emerald-50' : rejected ? 'border-rose-200 bg-rose-50' : 'border-primary/15 bg-primary/5'}`}><p className="text-xs font-semibold text-primary">STATUS PRIJAVE</p><p className="mt-1 flex items-center gap-2 font-semibold text-navy">{statusIcon} {statusLabel}</p><p className="mt-2 text-sm text-muted-foreground">Broj prijave: {application.id} · Paket: {application.plan}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[{ icon: FileCheck2, label: 'Dokumenta', text: approved ? 'Potvrđena' : 'Pregledaju se' }, { icon: ShieldCheck, label: 'Provera', text: approved ? 'Završena' : rejected ? 'Završena' : 'U toku' }, { icon: CheckCircle2, label: 'Aktivacija', text: approved ? 'Spremno za aktivaciju' : 'Nakon odobrenja' }].map((step) => { const Icon = step.icon; return <div key={step.label} className="rounded-2xl border border-border p-4"><Icon className="size-5 text-primary" /><p className="mt-3 text-sm font-semibold text-navy">{step.label}</p><p className="mt-1 text-xs text-muted-foreground">{step.text}</p></div> })}</div><Link href="/kontakt" className="mt-6 inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-sm font-semibold text-navy hover:border-primary"><Mail className="size-4" /> Kontaktiraj podršku</Link></> : <><p className="mt-2 text-muted-foreground">Nema prijave sačuvane na ovom uređaju. Pošalji prijavu partnera da bi njen status bio vidljiv ovde.</p><Link href="/partneri/registracija" className="mt-6 inline-flex rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Postani partner</Link></>}</section></div></main>
}
