import { BusinessCard } from "./business-card";
import { AppShell } from "./app-shell";
import { Badge, Button, SearchField, Tabs } from "./ui";
import { Icon } from "./icons";
import { businesses, jobs, moduleContent, transactions } from "../lib/demo-data";

export function ModulePage({ moduleKey }: { moduleKey: string }) {
  const content = moduleContent[moduleKey] ?? moduleContent.usluge;
  if (moduleKey === "novcanik") return <WalletScreen />;
  if (moduleKey === "poslovi") return <JobsScreen />;
  return <AppShell active="services"><section className={`module-hero accent-${content.accent}`}><span className="module-icon"><Icon name={content.icon} size={28}/></span><p>{content.eyebrow}</p><h1>{content.title}</h1><span>{content.description}</span><SearchField placeholder={`Pretraži: ${content.title.toLowerCase()}...`}/></section><section className="screen-section compact"><div className="filter-pills">{content.chips.map(chip => <button key={chip}>{chip}</button>)}</div><div className="module-feature-card"><div><Badge tone="ai" icon="sparkle">PREDLOG ZA TEBE</Badge><h2>{moduleKey === "putovanja" ? "Vikend u Istanbulu" : moduleKey === "dostava" ? "Najbolje ocenjen ručak u blizini" : "Pronađi rešenje bez komplikacija"}</h2><p>Personalizovana ponuda prema tvojoj lokaciji i onome što najčešće koristiš.</p><Button icon="send">{content.primary}</Button></div><span><Icon name={content.icon} size={54}/></span></div></section><section className="screen-section"><div className="section-title"><div><p>IZDVOJENO</p><h2>{moduleKey === "zdravlje" ? "Naredni termini" : "Preporučeno u blizini"}</h2></div><a href="/search">Prikaži sve</a></div><div className="business-list">{businesses.slice(0, 3).map(business => <BusinessCard business={business} key={business.id}/>)}</div>{content.notice && <p className="medical-notice"><Icon name="shield" size={17}/>{content.notice}</p>}</section></AppShell>;
}

function JobsScreen() { return <AppShell active="services"><section className="module-hero accent-violet"><span className="module-icon"><Icon name="briefcase" size={28}/></span><p>SLEDEĆA PRILIKA</p><h1>Poslovi</h1><span>Pronađi poziciju koja odgovara tvom iskustvu, gradu i načinu rada.</span><SearchField placeholder="Pretraži poslove..."/></section><section className="screen-section compact"><Tabs items={["Preporučeni", "Novi", "Sačuvani"]} active="Preporučeni"/><div className="job-list">{jobs.map(job => <article className="job-card" key={job.title}><span className="job-logo"><Icon name="briefcase" size={20}/></span><div><div className="job-card-top"><h2>{job.title}</h2>{job.fresh && <Badge tone="new">Novo</Badge>}</div><p>{job.company} · {job.place}</p><strong>{job.pay}</strong><small>{job.type}</small></div><button aria-label={`Sačuvaj oglas ${job.title}`}><Icon name="heart" size={18}/></button></article>)}</div></section></AppShell>; }

function WalletScreen() { return <AppShell active="services"><section className="module-hero accent-blue wallet-heading"><div className="wallet-topline"><span>Novčanik</span><Icon name="settings" size={19}/></div><div className="wallet-card wallet-full"><div className="wallet-card-head"><span>Dostupno stanje</span><Icon name="card" size={19}/></div><strong>12.450,00 <small>RSD</small></strong><p>IBAN: RS35 2850 0000 1234 5678 90</p><div><button><Icon name="plus" size={15}/> Dodaj novac</button><button><Icon name="send" size={15}/> Pošalji novac</button></div></div></section><section className="screen-section compact"><div className="wallet-menu">{[["card","Kartice"],["receipt","Računi"],["clock","Istorija"],["shield","Limiti"]].map(([icon,label]) => <a href="#" key={label}><Icon name={icon as "card"}/><span>{label}</span></a>)}</div><div className="section-title"><div><p>NEDAVNE TRANSAKCIJE</p><h2>Pregled troškova</h2></div><a href="#">Prikaži sve</a></div><div className="transaction-list">{transactions.map(transaction => <article key={transaction.name}><span className={`transaction-icon ${transaction.tone}`}><Icon name={transaction.icon} size={18}/></span><div><strong>{transaction.name}</strong><p>{transaction.detail}</p></div><b className={transaction.amount.startsWith("+") ? "positive" : ""}>{transaction.amount}</b></article>)}</div></section></AppShell>; }
