FROM node:22-alpine

WORKDIR /workspace

RUN corepack enable

COPY . .

RUN pnpm install --no-frozen-lockfile \
  && pnpm --filter @balkanworks/database prisma:generate

EXPOSE 3001

CMD ["pnpm", "--filter", "@balkanworks/api", "dev"]
