import { ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { BookingStatus, ConversationType, JobStatus, JobType, MarketplaceItemStatus, Prisma, ServiceProviderStatus, ServiceRequestStatus } from "@prisma/client";
import { PrismaService } from "@balkanworks/database";
import { Type } from "class-transformer";
import { ArrayMaxSize, IsArray, IsDateString, IsEnum, IsInt, IsNumber, IsOptional, IsString, IsUUID, Max, MaxLength, Min } from "class-validator";

export class CreateProviderDto { @IsOptional() @IsUUID() businessId?: string; @IsString() @MaxLength(2000) description!: string; @Type(() => Number) @IsInt() @Min(0) @Max(80) experienceYears!: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) priceFrom?: number; @IsOptional() @IsString() @MaxLength(80) location?: string; @IsArray() @ArrayMaxSize(12) @IsUUID("4", { each: true }) categoryIds!: string[]; }
export class CreateProviderServiceDto { @IsUUID() categoryId!: string; @IsString() @MaxLength(160) name!: string; @IsOptional() @IsString() @MaxLength(2000) description?: string; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) priceFrom?: number; }
export class CreateServiceRequestDto { @IsUUID() categoryId!: string; @IsOptional() @IsUUID() providerId?: string; @IsString() @MaxLength(2000) description!: string; @IsOptional() @IsString() @MaxLength(240) location?: string; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) budget?: number; }
export class CreateBookingDto { @IsUUID() serviceId!: string; @IsDateString() scheduledAt!: string; @IsOptional() @IsString() @MaxLength(240) location?: string; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) agreedPrice?: number; }
export class CreateJobDto { @IsUUID() businessId!: string; @IsString() @MaxLength(160) title!: string; @IsString() @MaxLength(6000) description!: string; @IsString() @MaxLength(100) category!: string; @IsEnum(JobType) type!: JobType; @IsOptional() @IsString() @MaxLength(160) location?: string; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) salaryMin?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) salaryMax?: number; }
export class ApplyJobDto { @IsOptional() @IsString() @MaxLength(3000) message?: string; @IsOptional() @IsString() @MaxLength(500) resumeUrl?: string; }
export class CreateMarketplaceItemDto { @IsString() @MaxLength(160) title!: string; @IsString() @MaxLength(5000) description!: string; @Type(() => Number) @IsNumber() @Min(0) price!: number; @IsString() @MaxLength(100) category!: string; @IsOptional() @IsString() @MaxLength(160) location?: string; @IsOptional() @IsArray() @ArrayMaxSize(10) @IsString({ each: true }) imageUrls?: string[]; }
export class SendMessageDto { @IsUUID() recipientId!: string; @IsString() @MaxLength(4000) content!: string; @IsOptional() @IsEnum(ConversationType) type?: ConversationType; @IsOptional() @IsString() @MaxLength(100) referenceId?: string; }
export class CreateReportDto { @IsString() @MaxLength(60) targetType!: string; @IsString() @MaxLength(100) targetId!: string; @IsString() @MaxLength(1000) reason!: string; }

@Injectable()
export class MarketplaceService {
  constructor(private readonly prisma: PrismaService) {}

  async categories() { return this.prisma.serviceCategory.findMany({ where: { deletedAt: null }, orderBy: { name: "asc" }, include: { children: { where: { deletedAt: null }, orderBy: { name: "asc" } } } }); }
  async providers(query?: string, category?: string, location?: string) {
    const where: Prisma.ServiceProviderWhereInput = { deletedAt: null, status: ServiceProviderStatus.ACTIVE, ...(location ? { location: { contains: location, mode: "insensitive" } } : {}), ...(category ? { categories: { some: { category: { slug: category } } } } : {}), ...(query ? { OR: [{ description: { contains: query, mode: "insensitive" } }, { user: { profile: { is: { firstName: { contains: query, mode: "insensitive" } } } } }, { business: { is: { name: { contains: query, mode: "insensitive" } } } }] } : {}) };
    return this.prisma.serviceProvider.findMany({ where, include: { user: { include: { profile: true } }, business: true, categories: { include: { category: true } }, services: { where: { isActive: true, deletedAt: null }, include: { category: true } } }, take: 50, orderBy: { updatedAt: "desc" } });
  }
  async provider(id: string) { const provider = await this.prisma.serviceProvider.findFirst({ where: { id, deletedAt: null, status: ServiceProviderStatus.ACTIVE }, include: { user: { include: { profile: true } }, business: true, categories: { include: { category: true } }, services: { where: { isActive: true, deletedAt: null }, include: { category: true } } } }); if (!provider) throw new NotFoundException("SERVICE_PROVIDER_NOT_FOUND"); return provider; }
  async createProvider(userId: string, input: CreateProviderDto) {
    if (input.businessId) await this.requireBusinessOwner(userId, input.businessId);
    const categories = await this.prisma.serviceCategory.count({ where: { id: { in: input.categoryIds }, deletedAt: null } }); if (categories !== input.categoryIds.length) throw new NotFoundException("SERVICE_CATEGORY_NOT_FOUND");
    return this.prisma.serviceProvider.upsert({ where: { userId }, create: { userId, businessId: input.businessId, description: input.description.trim(), experienceYears: input.experienceYears, priceFrom: input.priceFrom, location: input.location?.trim(), status: ServiceProviderStatus.ACTIVE, categories: { create: input.categoryIds.map((categoryId) => ({ categoryId })) } }, update: { businessId: input.businessId, description: input.description.trim(), experienceYears: input.experienceYears, priceFrom: input.priceFrom, location: input.location?.trim(), status: ServiceProviderStatus.ACTIVE, categories: { deleteMany: {}, create: input.categoryIds.map((categoryId) => ({ categoryId })) } }, include: { categories: { include: { category: true } } } });
  }
  async createProviderService(userId: string, input: CreateProviderServiceDto) { const provider = await this.requireProvider(userId); await this.requireCategory(input.categoryId); return this.prisma.providerService.create({ data: { providerId: provider.id, categoryId: input.categoryId, name: input.name.trim(), description: input.description?.trim(), priceFrom: input.priceFrom }, include: { category: true } }); }
  async createRequest(userId: string, input: CreateServiceRequestDto) { await this.requireCategory(input.categoryId); if (input.providerId) await this.provider(input.providerId); return this.prisma.serviceRequest.create({ data: { userId, categoryId: input.categoryId, providerId: input.providerId, description: input.description.trim(), location: input.location?.trim(), budget: input.budget }, include: { category: true, provider: true } }); }
  async acceptRequest(userId: string, requestId: string) { const provider = await this.requireProvider(userId); const request = await this.prisma.serviceRequest.findFirst({ where: { id: requestId, deletedAt: null, status: ServiceRequestStatus.OPEN } }); if (!request) throw new NotFoundException("SERVICE_REQUEST_NOT_FOUND"); return this.prisma.serviceRequest.update({ where: { id: request.id }, data: { providerId: provider.id, status: ServiceRequestStatus.ACCEPTED } }); }
  async book(userId: string, input: CreateBookingDto) { const service = await this.prisma.providerService.findFirst({ where: { id: input.serviceId, deletedAt: null, isActive: true }, include: { provider: true } }); if (!service?.provider || service.provider.userId === userId) throw new ForbiddenException("BOOKING_NOT_ALLOWED"); const scheduledAt = new Date(input.scheduledAt); if (Number.isNaN(scheduledAt.valueOf()) || scheduledAt <= new Date()) throw new ConflictException("BOOKING_TIME_INVALID"); const existing = await this.prisma.booking.findFirst({ where: { providerId: service.providerId, scheduledAt, status: { in: [BookingStatus.PENDING, BookingStatus.CONFIRMED, BookingStatus.IN_PROGRESS] } } }); if (existing) throw new ConflictException("BOOKING_SLOT_UNAVAILABLE"); return this.prisma.booking.create({ data: { serviceId: service.id, providerId: service.providerId, customerId: userId, scheduledAt, location: input.location?.trim(), agreedPrice: input.agreedPrice ?? service.priceFrom }, include: { service: true, provider: { include: { user: { include: { profile: true } } } } } }); }
  async listJobs(category?: string, location?: string) { return this.prisma.job.findMany({ where: { deletedAt: null, status: JobStatus.ACTIVE, ...(category ? { category: { equals: category, mode: "insensitive" } } : {}), ...(location ? { location: { contains: location, mode: "insensitive" } } : {}) }, include: { business: { select: { id: true, name: true, slug: true, logoUrl: true } }, _count: { select: { applications: true } } }, orderBy: { createdAt: "desc" }, take: 50 }); }
  async job(id: string) { const job = await this.prisma.job.findFirst({ where: { id, deletedAt: null, status: JobStatus.ACTIVE }, include: { business: { select: { id: true, name: true, slug: true, description: true, logoUrl: true } } } }); if (!job) throw new NotFoundException("JOB_NOT_FOUND"); return job; }
  async createJob(userId: string, input: CreateJobDto) { await this.requireBusinessOwner(userId, input.businessId); if (input.salaryMax != null && input.salaryMin != null && input.salaryMax < input.salaryMin) throw new ConflictException("INVALID_SALARY_RANGE"); return this.prisma.job.create({ data: { ...input, title: input.title.trim(), description: input.description.trim(), category: input.category.trim(), location: input.location?.trim(), status: JobStatus.ACTIVE } }); }
  async apply(userId: string, jobId: string, input: ApplyJobDto) { const job = await this.job(jobId); const isOwner = await this.prisma.job.findFirst({ where: { id: job.id, business: { ownerId: userId } } }); if (isOwner) throw new ForbiddenException("APPLICATION_NOT_ALLOWED"); return this.prisma.jobApplication.create({ data: { jobId: job.id, userId, message: input.message?.trim(), resumeUrl: input.resumeUrl?.trim() } }).catch(() => { throw new ConflictException("JOB_APPLICATION_EXISTS"); }); }
  async marketplace(category?: string, location?: string) { return this.prisma.marketplaceItem.findMany({ where: { deletedAt: null, status: MarketplaceItemStatus.ACTIVE, ...(category ? { category: { equals: category, mode: "insensitive" } } : {}), ...(location ? { location: { contains: location, mode: "insensitive" } } : {}) }, include: { seller: { include: { profile: true } } }, orderBy: { createdAt: "desc" }, take: 50 }); }
  async marketplaceItem(id: string) { const item = await this.prisma.marketplaceItem.findFirst({ where: { id, deletedAt: null, status: MarketplaceItemStatus.ACTIVE }, include: { seller: { include: { profile: true } } } }); if (!item) throw new NotFoundException("MARKETPLACE_ITEM_NOT_FOUND"); return item; }
  async createMarketplaceItem(userId: string, input: CreateMarketplaceItemDto) { return this.prisma.marketplaceItem.create({ data: { sellerId: userId, title: input.title.trim(), description: input.description.trim(), price: input.price, category: input.category.trim(), location: input.location?.trim(), imageUrls: input.imageUrls ?? [], status: MarketplaceItemStatus.ACTIVE } }); }
  async sendMessage(userId: string, input: SendMessageDto) { if (userId === input.recipientId) throw new ConflictException("MESSAGE_RECIPIENT_INVALID"); const recipient = await this.prisma.user.findFirst({ where: { id: input.recipientId, deletedAt: null, status: "ACTIVE" } }); if (!recipient) throw new NotFoundException("MESSAGE_RECIPIENT_NOT_FOUND"); const conversation = await this.prisma.conversation.create({ data: { type: input.type ?? ConversationType.GENERAL, referenceId: input.referenceId, participants: { create: [{ userId }, { userId: input.recipientId }] }, messages: { create: { senderId: userId, content: input.content.trim() } } }, include: { messages: true, participants: true } }); return conversation; }
  async conversations(userId: string) { return this.prisma.conversation.findMany({ where: { participants: { some: { userId } } }, include: { participants: { include: { user: { include: { profile: true } } } }, messages: { where: { deletedAt: null }, orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: 50 }); }
  async report(userId: string, input: CreateReportDto) { return this.prisma.report.create({ data: { userId, targetType: input.targetType.trim().toUpperCase(), targetId: input.targetId.trim(), reason: input.reason.trim() } }); }
  private async requireCategory(id: string) { const category = await this.prisma.serviceCategory.findFirst({ where: { id, deletedAt: null } }); if (!category) throw new NotFoundException("SERVICE_CATEGORY_NOT_FOUND"); return category; }
  private async requireProvider(userId: string) { const provider = await this.prisma.serviceProvider.findFirst({ where: { userId, deletedAt: null, status: ServiceProviderStatus.ACTIVE } }); if (!provider) throw new ForbiddenException("SERVICE_PROVIDER_REQUIRED"); return provider; }
  private async requireBusinessOwner(userId: string, businessId: string) { const business = await this.prisma.business.findFirst({ where: { id: businessId, ownerId: userId, deletedAt: null } }); if (!business) throw new ForbiddenException("BUSINESS_OWNERSHIP_REQUIRED"); return business; }
}
